config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:show, :new, :create] do
    resources :bookmarks, only: [:new, :create ]
  end
  resources :bookmarks, only: [:destroy]
  delete '/lists/:id', to: 'lists#destroy', as: :delete_list

  # Defines the root path route ("/")
  # root "articles#index"
  root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true
  validates :comment, length: { minimum: 6 }

  validates :list, presence: true, uniqueness: { scope: :movie_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  belongs_to :user
end

# A bookmark must be linked to a movie and a list, and the [movie, list] pairings should be unique.
# The comment of a bookmark cannot be shorter than 6 characters.

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :lists
  has_many :bookmarks
  validates :title, :overview, presence: true
  validates :title, :overview, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save

    if @bookmark.save
      redirect_to root_path, notice: "bookmark was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all

  end

  def show
    @list = List.find(params[:id])
    @bookmark = @list.bookmarks
    @list.user = current_user

  end

  def new
    @list = List.new
    @existing_list = List.first

  end

  def create
    @list = List.new(movies_params)
    @list.user = current_user

    if @list.save
      redirect_to root_path, notice: "list was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
  end

  def movies_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/destroy.html.erb
<h1> hello </h1>

app/views/bookmarks/index.html.erb
<h1> hello </h1>

<% @bookmarks.each do |bookmark|%>
<%= bookmark.comment %>
<% end %>

app/views/bookmarks/new.html.erb
<%= render 'shared/navbar2' %>
<div class="container vh-100 d-flex justify-content-center">
  <div class="row align-items-center">
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <h1>New Bookmark</h1>
      <%= f.input :comment %>
      <%= f.association :movie %>
      <%= f.submit "create", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= render 'shared/navbar' %>


<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://plus.unsplash.com/premium_photo-1683740128156-14c4ca18c69c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NjF8fG1vdmllc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60);">
  <div class="container">
    <h1> Rails WatchList</h1>
    <p> Bookmark your movies!</p>
  </div>
</div>
<div class="container">
  <div class="row p-4">
    <% current_user.lists.each do |list| %>
      <div class="col-lg-4 col-md-6 mb-4">
        <div class="card">
          <%= image_tag("https://images.unsplash.com/photo-1560109947-543149eceb16?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjF8fG1vdmllfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60", alt: "category image drama") %>
          <div class="card-body">
            <h5 class="card-title"><%= list.name %></h5>
            <a href="<%= list_path(list) %>" class="btn btn-primary blue-button" style="text-decoration: none;">View Details</a>
            <a href="<%=  delete_list_path(list) %>" data-turbo-method="delete" data-turbo-confirm="Are you sure?" class="btn btn-primary blue-button" style="text-decoration: none;">Delete this list</a>
          </div>
      </div>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<%= render 'shared/navbar2' %>
<div class="container vh-100 d-flex justify-content-center">
  <div class="row align-items-center">
    <h1>New list</h1>
      <%= simple_form_for @list  do |f| %>
        <%= f.input :name %>
        <%= f.input :genre %>
        <%= f.submit "create"%>
      <% end %>
    <p>
    </p>
  </div>
</div>

app/views/lists/show.html.erb
<%= render 'shared/navbar2' %>
<div class="container d-flex mt-4 justify-content-center vh-100 list-show">
    <h1> Your list </h1>
    <%= link_to 'add a bookmark', new_list_bookmark_path(@list), class:"btn btn-primary blue-button" %>
      <% @list.bookmarks.each do |bookmark|%>
        <h2>Movie Title: <%= bookmark.movie.title %> </h2>
          <h5> description: <%= bookmark.comment %> </h5>
          <h5> Movie Rating: <%= bookmark.movie.rating %> </h5>
          <h5> More Details: <%= bookmark.movie.overview %> </h5>
          <div class="container justify-content-center mt-4">
          <%= link_to 'delete this bookmark', bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: ' btn btn-primary blue-button mb-4' %>
          </div>
      <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar mt-2 p-4">
  <div class="container-fluid">
    <a class="navbar-brand">rails watch list</a>
    <form class="d-flex" role="search">
      <input class="form-control search-bar" type="search" placeholder="Search" aria-label="Search">
    <a href="<%= new_list_path %>" class="btn btn-primary blue-button" style="text-decoration: none;">create a new list</a>

    </form>
  </div>
</nav>

app/views/shared/_navbar2.html.erb
<nav class="navbar mt-2 p-4">
  <div class="container-fluid">
  <%= link_to 'My lists', root_path, class:"navbar-brand" %>
    <form class="d-flex" role="search">
    <% if @existing_list.present? %>
  <%= link_to 'Add a new bookmark', new_list_bookmark_path(@existing_list), class: 'btn btn-primary blue-button' %>
<% end %>
      <a href="<%= new_list_path %>" class="btn btn-primary blue-button" style="text-decoration: none;">create a new list</a>
    </form>
  </div>
</nav>